---
# tasks file for configure-slave-playbook


- name: Create ansible user
  user:
   name: ansible
   state: present
   generate_ssh_key: yes

- name: Create jenkins user
  user:
   name: jenkins
   state: present
   generate_ssh_key: yes

# Copy ssh keys to server

- name: Copy ansible SSH key to authorized keys
  authorized_key:
   user: ansible
   key: "{{ lookup('file', 'id_rsa.pub') }}"
   state: present

# Give then sudo rights with no passwd

- name: Add ansible sudo rights
  lineinfile:
   line: "ansible	ALL=(ALL)	NOPASSWD: ALL"
   path: /etc/sudoers
   state: present

- name: Restart SSH service
  service:
   name: sshd
   state: restarted

