---

- name: Install docker and ant
  become: yes
  gather_facts: no
  hosts: all


  tasks:


  - name: Ensure that docker and container-selinux are not present if clean_install is set to true
    yum:
     name:
      - docker
      - docker-common
      - container-selinux
     state: absent
    when: clean_install is defined and clean_install == True

  - name: Ensure yum-utils is installed
    yum:
     name: yum-utils
     state: present


  - name: Add docker repo
    yum_repository:
     name: docker-ce
     description: docker repo
     baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
     enabled: yes

  - name: Run 'yum clean all'
    command: yum clean all


  - name: Install docker
    yum:
     name: docker
     state: latest

  - name: Make sure docker starts on reboot and is currently started
    service:
     name: docker
     enabled: yes
     state: started

  - name: Make sure docker management group exists
    group:
     name: docker
     state: present

  - name: Add jenkins user to docker group
    user:
     name: jenkins
     group: docker
     append: yes

  - name: Restart jenkins service
    service:
     name: jenkins
     state: restarted
    when: "'masters' in group_names"

  - name: Install ant
    yum:
     name: ant
     state: present
