---

- name: Test role conditional
  hosts: localhost
  become: no
  gather_facts: no

  vars:
   run_task: false

  roles:


  - role: dummyrole
    vars:
     var1: test
     var2: hello
    when: run_task
